### ISSUE TITLE
Rename "X pages" to "X articles"

### ISSUE THREAD

**Issue by slifty** [OpenTechStrategies/SimpleBook#38]
The book UX currently references "pages" in things like info panes, but this is a misnomer since a given web page might translate to more than one printed page.

We should rename this to `articles`.

This issue was previously captured in #1

**Comment by slifty** [comment]
Question for @jim-mcgowan and @kfogel (as our resident linguistic pedant)

There are references to `pages` in other places, but it is often prefixed with `wiki`

e.g. `"Use drag & drop to reorder wiki pages and chapters"`

I imagine `wiki pages` would be better as `articles` as well and that's my plan, but thought I'd raise the concept of just renaming `X pages` to `X wiki pages` as an alternative solution.

**Comment by slifty** [comment]
Too late I've DECIDED: article is better all of the time.

**Comment by kfogel** [comment]
"proposal"

Just kidding -- "article" is fine.

**Comment by jim-mcgowan** [comment]
@slifty Not that I feel strongly, but as a layperson I think **wiki pages** makes more sense. The average Torque user probably won't think of the pages as _articles_.

**Comment by kfogel** [comment]
Well, "proposals" would be better than "wiki pages" for that, I think (as well as being more accurate, since some proposals involve multiple wiki pages, or at least multiple tabs of the same wiki page, which most users will likely think of as being different pages anyway).

How hard would it be to make this word configurable by admin?

**Comment by frankduncan** [comment]
The term of art in mediawiki is pages, and as far as I can tell, articles is rarely used.  For torque-sites, we can override i18n declarations for custom language for our wikis, but for the general open source use, "page" or "wiki page" is probably better.

**Comment by slifty** [comment]
@kfogel incredibly hard to make admin configurable -- this is defined in internationalization (and, I should note, we are only editing the english version here which is probably not great form).

Also, `"proposal"` isn't fully accurate since a proposal may have multiple tabs and each tab is added individually; and also you could add non-proposal pages (e.g. finalist lists, etc).

It sounds like there's some consensus on wiki page as opposed to article.

I'm going to let this issue sit overnight so folks can weigh in before I open a new PR implementing that.

**Comment by kfogel** [comment]
I'd really like to move away from having Torque's implementation show through so much.  Yes, it's built on a wiki, but its users aren't behaving like editors of a wiki, for the most part, and many of the non-LFC users are (I suspect?) not thinking of themselves as being in a wiki at all when they use Torque.

We can't use "pages" by itself: that term is very confusing when it comes to book printing, for obvious reasons.  I'd like to not use "wiki pages" both because it has the word "pages" in it (hence confusion) and because it has the word "wiki" in it (hence implementation showing through).

I think "article" is a good compromise.  I'm happy to sleep on it and discuss at our meeting tomorrow, too.
